const data = {
    products: [{
            name: 'olma',
            slug: 'bu-ajoyib-olma',
            catagory: 'meva',
            image: './images/olma.jpeg',
            price: 15000,
            countInstock: 10,
            brand: 'Bahmal-olamalari',
            rayting: 4.5,
            izohlarSoni: 15,
            description: 'Bahmal toglarida yetishtirilgan, suvli shirin olma',
        },
        {
            name: 'anor',
            slug: 'anormisan-anor',
            catagory: 'meva',
            image: './images/anor.jpeg',
            price: 30000,
            countInstock: 10,
            brand: 'Syrxon vohasi',
            rayting: 4.9,
            izohlarSoni: 30,
            description: 'Qora donali, nardon, ishtaxa ochar va shifobaxsh, suvli anor',
        },
        {
            name: 'banan',
            slug: 'Jamayka banani',
            catagory: 'meva',
            image: './images/banan.jpeg',
            price: 17000,
            countInstock: 8,
            brand: 'Bananas Jamaica',
            rayting: 4,
            izohlarSoni: 200,
            description: 'Jamaica lahm bananlari, tuyimli va etdor, shirin, tez hazm buluvchi',
        },
        {
            name: 'peach',
            slug: 'Qorakissa Oq tosh bogidan',
            catagory: 'meva',
            image: './images/peach.jpeg',
            price: 20000,
            countInstock: 10,
            brand: 'QorakissaPeach',
            rayting: 4.9,
            izohlarSoni: 60,
            description: 'Qorakissa Oq tog bagrida yetishtirilgan, sharbatli, momiq shaftoli',
        },
    ],
};